# Generated by Django 3.2.1 on 2022-07-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='last_edit',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
