# Generated by Django 3.2.1 on 2022-10-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='url',
        ),
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.CharField(default='uninitialized-page', max_length=200),
        ),
    ]
