# Generated by Django 3.2.1 on 2022-07-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0002_alter_file_last_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='last_edit',
            field=models.DateTimeField(null=True),
        ),
    ]
