# Generated by Django 3.2.1 on 2022-10-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0002_auto_20221004_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
