# Generated by Django 3.2.1 on 2022-06-30 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0002_auto_20220629_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='cells',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='files',
        ),
        migrations.AddField(
            model_name='cell',
            name='main_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wikiapp.file'),
        ),
        migrations.AddField(
            model_name='file',
            name='notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wikiapp.notebook'),
        ),
    ]
