# Generated by Django 3.2.1 on 2022-10-04 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0003_alter_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='last_edit',
        ),
    ]
