# Generated by Django 3.2.1 on 2022-10-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0004_remove_notebook_last_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.CharField(editable=False, max_length=200, unique=True),
        ),
    ]
