# Generated by Django 3.2.1 on 2022-10-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0005_alter_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
