# Generated by Django 3.2.1 on 2022-07-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0006_auto_20220721_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='main_file',
        ),
    ]
