# Generated by Django 3.2.1 on 2022-10-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0006_alter_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='last_edit',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
