# Generated by Django 3.2.1 on 2022-07-21 15:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0007_remove_cell_main_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='id',
        ),
        migrations.AlterField(
            model_name='cell',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
