# Generated by Django 3.2.1 on 2022-10-26 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0007_alter_file_last_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='main_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wikiapp.file'),
        ),
    ]
