# Generated by Django 3.2.1 on 2022-10-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0008_alter_cell_main_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cell',
            old_name='main_file',
            new_name='mf',
        ),
    ]
