# Generated by Django 3.2.1 on 2022-10-03 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0008_auto_20220721_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='main_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wikiapp.file'),
        ),
    ]
